rmcgirr83_nationalflags_display:
    path: /flags
    defaults: { _controller: rmcgirr83.nationalflags.main.controller:displayFlags }

rmcgirr83_nationalflags_getflag:
    pattern: /flag/{flag_id}
    defaults: { _controller: rmcgirr83.nationalflags.main.controller:getFlag }

rmcgirr83_nationalflags_getflags:
    pattern: /flags/{flag_name}
    defaults: { _controller: rmcgirr83.nationalflags.main.controller:getFlags, page: 1}

rmcgirr83_nationalflags_getflags_page:
    pattern: /flags/{flag_name}/page/{page}
    defaults: { _controller: rmcgirr83.nationalflags.main.controller:getFlags}
