imports:
    - { resource: tables.yml }

services:
    rmcgirr83.nationalflags.acp:
        class: rmcgirr83\nationalflags\acp\nationalflags_module
        arguments:
            - @dbal.conn
            - %rmcgirr83.nationalflags.tables.nationalflags%
    rmcgirr83.nationalflags.listener:
        class: rmcgirr83\nationalflags\event\listener
        arguments:
            - @rmcgirr83.nationalflags.functions
            - @config
            - @controller.helper
            - @dbal.conn
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }
    rmcgirr83.nationalflags.functions:
        class: rmcgirr83\nationalflags\core\functions_nationalflags
        arguments:
            - @auth
            - @config
            - @cache
            - @content.visibility
            - @dbal.conn
            - @dispatcher
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%